# -- Dataset Options --
input_resolution: [128, 128]

# -- Training Options --
batch_size: 32
train_steps: 2.5E+5 
rng_seed: 822309

# -- Optimizer Options -- 
learning_rate: 0.0004
adam_beta_1: 0.9 
adam_beta_2: 0.999 
adam_eps: 1.0E-8 
lr_decay_rate: 0.5 
weight_decay: 1.0E-6
warmup_iter: 1.0E+4 
decay_steps: 1.0E+5

# -- SA+ST Options --
mlp_hidden_size: 48
spatial_broadcast_dims: [8,8] 
hidden_res: [128,128] 
slots: 4
reco_layers: 2 # For reconstruction
attn_iter: 3
slot_size: 64
attention_eps: 1.0E-8
encoder_cnn_channels: [64,64,64,64] 
encoder_cnn_kernels: [5,5,5,5]
encoder_cnn_strides: [1,1,1,1] 
decoder_cnn_channels: [64,64,64,64,64] 
decoder_cnn_kernels: [5,5,5,3]
decoder_cnn_strides: [2,2,1,1] 
extra_deconv_layers: 1 
resolution: [128,128]

