# -- Dataset Options --
input_resolution: [64, 64]

# -- Training Options --
batch_size: 32
train_steps: 5 # 2.5E+5 # 10 runs per experiment - 10*50k
rng_seed: 822314

# -- Optimizer Options -- 
learning_rate: 0.0004
adam_beta_1: 0.9 #type=float)
adam_beta_2: 0.999 #type=float)
adam_eps: 1.0E-8 #type=float)
lr_decay_rate: 0.5 #type=float)
weight_decay: 1.0E-6
warmup_iter: 1.0E+4 #type=float)
decay_steps: 1.0E+5 #type=float)

# -- SA Options --
mlp_hidden_size: 64
spatial_broadcast_dims: [128,128] 
hidden_res: [128,128] 
slots: 10
reco_layers: 2 # For reconstruction
attn_iter: 3
slot_size: 32 # They use 64 for all experiments
attention_eps: 1.0E-8 
encoder_cnn_channels: [32,32,32,32] 
encoder_cnn_kernels: [5,5,5,5] 
encoder_cnn_strides: [1,1,1,1] 
decoder_cnn_channels: [32,32,32] # Channels in 3 decoding CNN layers (final one = inp_channels+1)")
decoder_cnn_kernels: [5,5,5,3] 
decoder_cnn_strides: [1,1,1,1] 
extra_deconv_layers: 0  # True for CLEVR 
resolution: [36,36]

